# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-20 17:55
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address_Detail',
            fields=[
                ('current_address', models.CharField(default=None, max_length=40, primary_key=True, serialize=False)),
                ('current_city', models.CharField(default=None, max_length=40)),
                ('current_province', models.CharField(default=None, max_length=40)),
                ('current_country', models.CharField(default=None, max_length=40)),
                ('mailing_address', models.CharField(default=None, max_length=60)),
                ('mailing_city', models.CharField(default=None, max_length=40)),
                ('mailing_state', models.CharField(default=None, max_length=40)),
                ('mailing_country', models.CharField(default=None, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Certification_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certi_title', models.CharField(default=None, max_length=40)),
                ('certi_body', models.CharField(default=None, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Company_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_address', models.CharField(default=None, max_length=80)),
                ('company_city', models.CharField(default='Windsor', max_length=40)),
                ('company_province', models.CharField(default='Ontario', max_length=40)),
                ('company_postalcode', models.CharField(default=None, max_length=40)),
                ('company_country', models.CharField(default='Canada', max_length=40)),
                ('company_contact_fname', models.CharField(default=None, max_length=40)),
                ('company_contact_lname', models.CharField(default=None, max_length=40)),
                ('company_contact_position', models.CharField(default=None, max_length=40)),
                ('company_phone', models.IntegerField(default=None)),
                ('company_email', models.EmailField(default=None, max_length=254)),
                ('company_website', models.URLField(default=None)),
                ('company_note', models.TextField(default=None)),
                ('certification_detail', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.Certification_Detail')),
            ],
        ),
        migrations.CreateModel(
            name='Education_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(default=None, max_length=40)),
                ('degree_title', models.CharField(default=None, max_length=40)),
                ('degree_cpga', models.CharField(default=None, max_length=40)),
                ('degree_university', models.CharField(default=None, max_length=60)),
                ('degree_university_location', models.CharField(default=None, max_length=60)),
                ('degree_start_month', models.IntegerField(default=None)),
                ('degree_end_month', models.IntegerField(default=None)),
                ('degree_start_year', models.IntegerField(default=None)),
                ('degree_end_year', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(choices=[('st', 'Student'), ('fc', 'Faculty'), ('sf', 'Staff')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Internship_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship_type', models.CharField(default=None, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_position', models.CharField(default=None, max_length=60)),
                ('job_description', models.CharField(default=None, max_length=40)),
                ('job_salery', models.CharField(default=None, max_length=40)),
                ('job_company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.Company_Detail')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_group_description', models.CharField(default=None, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Requirment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_req_desc', models.CharField(default=None, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Responsibilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_resp_desc', models.CharField(default=None, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_status', models.CharField(choices=[('un', 'Unopened'), ('op', 'Open'), ('cl', 'Closed')], default=None, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Semester_Registered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(default=None, max_length=60)),
                ('semester_year', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_fname', models.CharField(default=None, max_length=40)),
                ('student_mname', models.CharField(default=None, max_length=40)),
                ('student_lname', models.CharField(default=None, max_length=40)),
                ('student_phone', models.IntegerField(default=None)),
                ('student_gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default=None, max_length=1)),
                ('student_choice', models.CharField(choices=[('i', 'International'), ('p', 'Permanent Resident')], default=None, max_length=1)),
                ('student_current_past_choices', models.CharField(choices=[('cs', 'Current Student'), ('ps', 'Past Student')], default=None, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Internship_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_detail', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.Job_Detail')),
            ],
        ),
        migrations.CreateModel(
            name='User_Auth',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('usr_id', models.CharField(default=None, max_length=40)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='semester_registered',
            name='student_detail',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.Student_Detail'),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='job_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.Job_Group'),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='job_internship_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.Internship_Type'),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='job_requirment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.Job_Requirment'),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='job_responsibility',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.Job_Responsibilities'),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='job_status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.Job_Status'),
        ),
        migrations.AddField(
            model_name='group',
            name='user_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.User_Auth'),
        ),
    ]
