# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-21 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education_detail',
            name='st_fname',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.Student_Detail'),
        ),
    ]
